spring:
  h2:
    console: true
  datasource:
    url: jdbc::h2:mem:system
    username: root
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
